version: '3.9'
services:
  database:
    container_name: media-monk-message-db
    image: 'postgres:15.1'
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ~/docker-data/media-monk-message-db:/var/lib/postgresql/data
      - ./postgress/message-schema.sql:/docker-entrypoint-initdb.d/message-schema.sql

  service:
    container_name: media-monk-message-service
    build:
      context: ./MediaMonkAssignment
    restart: always
    ports:
      - 8080:8080
    links:
      - database