version: '3.9'
services:
  database:
    container_name: media-monk-message-db
    image: 'postgres:15.1'
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ~/docker-data/media-monk-message-db:/var/lib/postgresql/data
      - ./postgress/message-schema.sql:/docker-entrypoint-initdb.d/message-schema.sql

  service:
    container_name: media-monk-message-service
    build:
      context: ./MediaMonkAssignment
    restart: always
    ports:
      - 8080:8080
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - database
    links:
      - database
  nodejs-server:
    container_name: media-monk-node-message-server
    build:
      context: ./nodeJsMediaMonkAssignment
    ports:
      - 3000:3000